# Generated by Django 2.1.7 on 2019-08-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu_rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
            ],
        ),
    ]
