# Generated by Django 2.1.7 on 2019-08-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu_rank', '0002_submits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='avatarUrl',
        ),
    ]
